
@startuml

participant "IMediaPosition\n(RSAdsProxy)" as PositionProxy
participant "IAdsPlayerProxy\n(RSAdsProxy)" as Proxy
participant "CowatchAdsEngine\n(RSAdCowatchBridge)" as Engine
participant "IAdsService\n(RSAdsProxy)" as Repository
participant "IMediaSync\n(RSAdsProxy)" as MediaSync

== Video Start ==

PositionProxy --> Engine: OnPlaybackTick(timestamp)
note right: This callback is called frequently \n with the media's current timestamp

...1 minute later...

Engine -> Repository: Get Ad Insertion Points
Repository -> Engine: Insertion points for Media

...5 minutes before ad insertion time...

== Request Ads ==
Engine -> Repository: Get Ad For Media
Repository --> Engine: Ad For Media

...4 minutes later...

== Preload Ads ==
Engine -> Proxy: Preload Ad

...1 minute later...

== Play Ads ==
Engine -> Proxy: Play Ad
Engine -> MediaSync: PAUSE_WT_MEDIA

... 30 seconds later...

== Ad Break Complete ==
Engine <- Proxy: Ad Playback Complete
Engine -> MediaSync: PLAY_WT_MEDIA

@enduml
