@startuml


class IMediaPosition {
    void OnPlaybackTime(time)
}


class iOs_MSYS_Goop{
}

class Shared_Android_Portal_GQL_To_AdService{
}

class IAdService {
    void GetInsertionPoints()
    void GetAdd()
}

IAdService <|--  Shared_Android_Portal_GQL_To_AdService
IAdService <|--  iOs_MSYS_Goop


class MSGR_CowatchPlayer{
}
class Portal_Player{
}
MSGR_CowatchPlayer --|> IMediaPosition : calls
Portal_Player --|> IMediaPosition : calls

@enduml