@startuml
autonumber
actor "Browser\n(Chrome)" as browser
participant "Azure function \n(https://manager-book.azurewebsites.net)" as azure_function
participant "Jekyll blog \n (https://idvork.in/the-manager-book)" as the_manager_book
browser -> azure_function: https://manager-book.azurewebsites.net/my-topic
activate azure_function
note right
 get path and convert it to anchor and title. e.g:
    title =  "My topic"
    redirect = "https://idvork.in/the-manager-book#my-topic"
end note
browser <-- azure_function: HTML {title=...,redirect=...}
destroy azure_function
browser --> the_manager_book: https://idvork.in/the-manager-book
browser --> the_manager_book: Scroll to #my-topic


@enduml